# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PritStik
description: >- # this means to ignore newlines until "baseurl:"
  PritStik
author: Michael James
baseurl: "/pritstik" # the subpath of your site, e.g. /blog
url: "https://alephnaughtpix.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
port: 4000
show_excerpts: True
sass:
  style: compressed

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - src/
   - scripts/
   - README.md

collections:
  songs:
    output: true
    permalink: "/music/songs/:slug.html"
    
defaults:
  - scope:
     path: ""
    values:
      root_index: "/index.html"
      info_index: "/info/index.html"
      music_index: "/music/index.html"
      cd_index: "/music/cd.html"
      mrr_index: "/mrr/index.html"
      studio_link: "/info/recording.html#Studios"
      instruments_link: "/info/recording.html#Instruments"
  - scope:
      path: ""
      type: "songs"
    values:
      layout: "song"
      title: "M U S I C"
      navigation: "music"
